name: Java Spring Boot CI/CD

on:
  push:
    paths:
      - 'real-estate-backend/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'real-estate-backend/**'
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests with Maven
        working-directory: real-estate-backend
        run: mvn clean test